package ss.project.shared.model;

/**
 * A very simple model class that contains a list of NAMES.
 * Used to automatically give the players a name in singleplayer.
 * Created by simon on 28.01.17.
 */
public class NameList {
    /**
     * A list of random NAMES.
     */
    public static final String[] NAMES =
        {
        "Irene Scoggins",
        "Claude Roubidoux",
        "Mollie Buchanan",
        "Arthur Power",
        "Denise Martins",
        "Mary Torres",
        "Samuel Burton",
        "James Federline",
        "John Freeman",
        "Joan Flemming",
        "Debra Anderson",
        "Ashley Levasseur",
        "Tyson Smith",
        "Teresa Higgs",
        "Troy Brown",
        "Loren Johnson",
        "Christopher Agnew",
        "Laure Krajewski",
        "Bettye Esch",
        "Gladys Managan",
        "Audra Fuller",
        "Tanya Koehler",
        "Johnnie Roylance",
        "Stevie Brock",
        "Renee Miller",
        "Diane Greene",
        "Jayson Jackson",
        "Linda Meza",
        "Cristina Prisco",
        "Janet Garcia",
        "Donna Herrington",
        "Lois Lee",
        "Deborah Pinder",
        "Darren Boak",
        "Matthew Ramirez",
        "Lee Duke",
        "Heather Miller",
        "Dan Nelson",
        "Pauline Varela",
        "Thomas Aliu",
        "Debra Cramer",
        "April Howard",
        "Vincent Schlotterbeck",
        "Willie Wooten",
        "Patricia Canseco",
        "James Bell",
        "Michelle Pope",
        "Andrew Berlin",
        "Suzann Young",
        "Lawrence Sharpe",
        "Norma Vera",
        "Lucinda Sansone",
        "David Vanness",
        "Sasha Richardson",
        "Matthew Clark",
        "John Teems",
        "Brandon Fornal",
        "Neil Flores",
        "Melissa Morgan",
        "Marie Wingo",
        "Peter Cline",
        "Kandice Michaud",
        "Molly Garcia",
        "Debra Mulvihill",
        "Terry Mccormick",
        "Doris Patterson",
        "Melissa Kiker",
        "Douglas Banks",
        "Melissa Potter",
        "Felicia Mccreary",
        "Gary Wilson",
        "Joseph Ririe",
        "Marty Baylor",
        "Franklin Carlson",
        "Jennifer Lucero",
        "Mabel Smith",
        "Charles Riccitelli",
        "Howard Black",
        "Valerie Burgess",
        "Katherine Zamzow",
        "Billy Garcia",
        "Frank Davenport",
        "Nick Harris",
        "Henry Smith",
        "Jason Buitrago",
        "Roger Talley",
        "Kenneth Wallis",
        "Mary Stringer",
        "Elizabeth Larson",
        "Heather Ruecker",
        "James Benjamin",
        "Larry Roche",
        "Keith Henderson",
        "Marilyn Macko",
        "Sheila Garza",
        "Jason Mesa",
        "Ricky Brookes",
        "Edgar Uphoff",
        "David Dickinson",
        "Lavonia Cortez"};
}
